"""Add refresh token and for test session

Revision ID: 040978e245fb
Revises: 7b3383d59175
Create Date: 2025-11-26 12:12:28.898071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '040978e245fb'
down_revision: Union[str, Sequence[str], None] = '7b3383d59175'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'articles', ['module_item_pk'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='unique')
    # ### end Alembic commands ###
