"""empty message

Revision ID: 06d01ecd7692
Revises: 0636ef52a1c8
Create Date: 2026-02-03 15:11:24.057481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06d01ecd7692'
down_revision: Union[str, Sequence[str], None] = '0636ef52a1c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('static_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('icon_pk', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['icon_pk'], ['static_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('achievement_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_pk', sa.Integer(), nullable=False),
    sa.Column('user_pk', sa.Integer(), nullable=False),
    sa.Column('date_received', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['achievement_pk'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['user_pk'], ['userprofiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('achievement_users')
    op.drop_table('achievements')
    op.drop_table('static_resources')
    # ### end Alembic commands ###
