"""Add Question and article


Revision ID: 1bea3413f825
Revises: db2f41a16e70
Create Date: 2025-11-19 12:24:17.245340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bea3413f825'
down_revision: Union[str, Sequence[str], None] = 'db2f41a16e70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('single', 'multiple', 'text', name='questiontype'), nullable=False),
    sa.Column('test_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_pk'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionsanswers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('question_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionsanswers')
    op.drop_table('questions')
    op.drop_table('tests')
    op.drop_table('articles')
    # ### end Alembic commands ###
