"""Add session items

Revision ID: 36409e01be28
Revises: 7d8017efcec7
Create Date: 2026-01-10 15:05:05.787927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36409e01be28'
down_revision: Union[str, Sequence[str], None] = '7d8017efcec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_session_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_session_token', sa.String(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['test_session_token'], ['test_session_tokens.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('title', sa.String(), nullable=False))
    op.alter_column('module_items', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('module_items_article_id_fkey'), 'module_items', type_='foreignkey')
    op.create_foreign_key(None, 'module_items', 'articles', ['article_id'], ['id'], ondelete='CASCADE')
    op.drop_column('module_items', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('module_items', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'module_items', type_='foreignkey')
    op.create_foreign_key(op.f('module_items_article_id_fkey'), 'module_items', 'articles', ['article_id'], ['id'], ondelete='SET NULL')
    op.alter_column('module_items', 'article_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('articles', 'title')
    op.drop_table('test_session_items')
    # ### end Alembic commands ###
