"""empty message

Revision ID: 8dda7a00ef8b
Revises: 06d01ecd7692
Create Date: 2026-02-09 10:58:00.288437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dda7a00ef8b'
down_revision: Union[str, Sequence[str], None] = '06d01ecd7692'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['articles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('article_pk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_pk'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('user_article_completions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'article_id')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_pk', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('SINGLE', 'MULTIPLE', 'SELECTABLE', name='answertype'), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_pk'], ['quiz_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_pk', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempt_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quiz_attempt_pk', sa.String(), nullable=False),
    sa.Column('question_pk', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_pk'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_attempt_pk'], ['quiz_attempts.token'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quiz_attempt_pk', 'order_index')
    )
    op.create_unique_constraint(None, 'module_items', ['module_id', 'order_index'])
    op.add_column('modules', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('modules', 'need_to_unlook')
    op.drop_constraint(op.f('userprofiles_user_id_key'), 'userprofiles', type_='unique')
    op.drop_constraint(op.f('userprofiles_user_id_fkey'), 'userprofiles', type_='foreignkey')
    op.drop_constraint(op.f('userprofiles_id_fkey'), 'userprofiles', type_='foreignkey')
    op.create_foreign_key(None, 'userprofiles', 'users', ['id'], ['id'], ondelete='CASCADE')
    op.drop_column('userprofiles', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofiles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userprofiles', type_='foreignkey')
    op.create_foreign_key(op.f('userprofiles_id_fkey'), 'userprofiles', 'users', ['id'], ['id'])
    op.create_foreign_key(op.f('userprofiles_user_id_fkey'), 'userprofiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('userprofiles_user_id_key'), 'userprofiles', ['user_id'], postgresql_nulls_not_distinct=False)
    op.add_column('modules', sa.Column('need_to_unlook', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('modules', 'description')
    op.drop_constraint(None, 'module_items', type_='unique')
    op.drop_table('quiz_attempt_questions')
    op.drop_table('answers')
    op.drop_table('questions')
    op.drop_table('user_article_completions')
    op.drop_table('quiz_attempts')
    op.drop_table('quiz_articles')
    # ### end Alembic commands ###
