"""empty message

Revision ID: 8e80c7ca3efb
Revises: 1bea3413f825
Create Date: 2025-11-23 08:01:00.015829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e80c7ca3efb'
down_revision: Union[str, Sequence[str], None] = '1bea3413f825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('test_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'tests', ['test_pk'], ['id'])
    op.drop_column('articles', 'order_index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('order_index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'test_pk')
    # ### end Alembic commands ###
