"""Add refresh token and for test session

Revision ID: 95e881bbfd1d
Revises: 040978e245fb
Create Date: 2025-11-26 12:14:26.480127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95e881bbfd1d'
down_revision: Union[str, Sequence[str], None] = '040978e245fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('test_session_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_session_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
