"""Make refationship Module Item and Article

Revision ID: 97c1b5fb00a4
Revises: 16fc5daa0579
Create Date: 2025-11-24 11:51:28.762629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97c1b5fb00a4'
down_revision: Union[str, Sequence[str], None] = '16fc5daa0579'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('module_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('articles', sa.Column('module_item_pk', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'articles', 'module_items', ['module_item_pk'], ['id'])
    op.alter_column('userprofiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofiles', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'module_item_pk')
    op.drop_table('module_items')
    op.drop_table('modules')
    # ### end Alembic commands ###
