"""empty message

Revision ID: dca080868dfe
Revises: f857fe05a781
Create Date: 2025-12-03 05:41:19.464118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dca080868dfe'
down_revision: Union[str, Sequence[str], None] = 'f857fe05a781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'title')
    op.add_column('module_items', sa.Column('title', sa.String(), nullable=False))
    op.drop_constraint(op.f('module_items_module_id_fkey'), 'module_items', type_='foreignkey')
    op.create_foreign_key(None, 'module_items', 'modules', ['module_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module_items', type_='foreignkey')
    op.create_foreign_key(op.f('module_items_module_id_fkey'), 'module_items', 'modules', ['module_id'], ['id'])
    op.drop_column('module_items', 'title')
    op.add_column('articles', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
