"""Update fk

Revision ID: f857fe05a781
Revises: 183438633e22
Create Date: 2025-11-28 18:37:13.347096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f857fe05a781'
down_revision: Union[str, Sequence[str], None] = '183438633e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('articles_module_item_pk_key'), 'articles', type_='unique')
    op.drop_constraint(op.f('articles_module_item_pk_fkey'), 'articles', type_='foreignkey')
    op.drop_constraint(op.f('articles_test_pk_fkey'), 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'tests', ['test_pk'], ['id'], ondelete='SET NULL')
    op.drop_column('articles', 'module_item_pk')
    op.add_column('module_items', sa.Column('article_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'module_items', 'articles', ['article_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('questions_test_pk_fkey'), 'questions', type_='foreignkey')
    op.create_foreign_key(None, 'questions', 'tests', ['test_pk'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('questionsanswers_question_pk_fkey'), 'questionsanswers', type_='foreignkey')
    op.create_foreign_key(None, 'questionsanswers', 'questions', ['question_pk'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'userprofiles', ['user_id'])
    op.drop_constraint(op.f('userprofiles_user_id_fkey'), 'userprofiles', type_='foreignkey')
    op.create_foreign_key(None, 'userprofiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofiles', type_='foreignkey')
    op.create_foreign_key(op.f('userprofiles_user_id_fkey'), 'userprofiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'userprofiles', type_='unique')
    op.drop_constraint(None, 'questionsanswers', type_='foreignkey')
    op.create_foreign_key(op.f('questionsanswers_question_pk_fkey'), 'questionsanswers', 'questions', ['question_pk'], ['id'])
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.create_foreign_key(op.f('questions_test_pk_fkey'), 'questions', 'tests', ['test_pk'], ['id'])
    op.drop_constraint(None, 'module_items', type_='foreignkey')
    op.drop_column('module_items', 'article_id')
    op.add_column('articles', sa.Column('module_item_pk', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key(op.f('articles_test_pk_fkey'), 'articles', 'tests', ['test_pk'], ['id'])
    op.create_foreign_key(op.f('articles_module_item_pk_fkey'), 'articles', 'module_items', ['module_item_pk'], ['id'])
    op.create_unique_constraint(op.f('articles_module_item_pk_key'), 'articles', ['module_item_pk'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
