"""empty message

Revision ID: fae36a1c2b1e
Revises: c8fad1e0e381
Create Date: 2025-11-18 14:31:55.185197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fae36a1c2b1e'
down_revision: Union[str, Sequence[str], None] = 'c8fad1e0e381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofiles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'userprofiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofiles', type_='foreignkey')
    op.drop_column('userprofiles', 'user_id')
    # ### end Alembic commands ###
