services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: user_dev
      POSTGRES_PASSWORD: qweasdzxc123
      POSTGRES_DB: test_dev
    volumes:
      - pg_data_dev:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: dev
    volumes:
      - "./backend:/app:z"
    ports:
      - "8000:8000"

volumes:
  pg_data_dev:
