# pytest.ini
[pytest]


# Поиск тестов
python_files = test_*.py *_test.py
python_classes = *Test  # классы, начинающиеся с Test
python_functions = test_*  # функции, начинающиеся с test_

# Игнорировать предупреждения при коллекции
filterwarnings =
    ignore::pytest.PytestCollectionWarning
